# Generated by Django 2.2.19 on 2024-11-17 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tg_username', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, default='nophoto.jpeg', null=True, upload_to='images/', verbose_name='Фото_<django.db.models.fields.CharField>')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tg_username', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=12)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('open_close', models.BooleanField(default=True)),
                ('on_main', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='nopstorephoto.jpeg', null=True, upload_to='images/', verbose_name='Store_<django.db.models.fields.CharField>')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.CategoryStore')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница'), ('Saturday', 'Суббота'), ('Sunday', 'Воскресенье')], max_length=10)),
                ('openig_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_opened', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='shop.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('on_main', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='noproductphoto.jpeg', null=True, upload_to='images/', verbose_name='Product_<django.db.models.fields.CharField>')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.CategoryProduct')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Client')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Store')),
            ],
        ),
    ]
