# Generated by Django 2.2.19 on 2024-11-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_ordernumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderNumber',
        ),
    ]
