# Generated by Django 2.2.19 on 2024-11-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20241125_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinghour',
            old_name='openig_time',
            new_name='opening_time',
        ),
    ]
